name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Cada medianoche
  workflow_dispatch: # Para ejecutarlo tú a mano

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: robleslf
          output_path: trophy.svg
          theme: shadow_blue
          # Nota: He quitado 'column' porque no es un parámetro válido aquí.

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git commit -m "Update trophies" || exit 0
          git push
